### PR TITLE
Support Go module

### PR DESCRIPTION
**Pull request by zchee**
Support Go module. separate `slack` library and `cmd/slapoxy` for avoid unnecessary dependencies.

### CODE REVIEW

**Comment by lestrrat** [comment]
from various reports in the wild, I think it's (sometimes) problematic to include a go.sum file. Can we just do away with go.mod for now?

**Comment by zchee** [comment]
respect your opinion, close it :)

**Comment by lestrrat** [comment]
@zchee あれ、伝わってないぞーw

go.modはOKなんだけど、go.sumが時々問題あるので、go.modだけはどう？というコメントでした！

**Comment by zchee** [comment]
lol, will reopen

**Comment by zchee** [comment]
@lestrrat reopened #64

**Pull request closed without merging**
